[package]
name = "hyprland-lang-notifier"
version = "0.1.0"
edition = "2021"
description = "Displays desktop notification when language changes in Hyprland."

[dependencies]
hyprland = "0.3.3"
notify-rust = "4.8.0"
