# [[file:../../../../new_project.org::*Uranium specific hardware][Uranium specific hardware:1]]
{ pkgs, lib, ... }:
{
  imports = [ ./frame.work.nix ];
  boot = {
    loader = {
      # Use the systemd-boot EFI boot loader.
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;

      # Limit space occupied by generations in boot
      grub.configurationLimit = 5;
    };
    tmp = {
      useTmpfs = true;
      tmpfsSize = "8G";
    };
    kernelModules = [
      "kvm-amd"
      "coretemp"
    ];
    extraModulePackages = [ ];
    # Frame.work needs latest kernel for BT and Wi-Fi to work.
    kernelPackages = pkgs.linuxPackages_latest;
    initrd = {
      # Modules I want to ensure are there
      availableKernelModules = [
        "thunderbolt"
        "nvme"
        "usb_storage"
        "uas"
      ];
      kernelModules = [ ];
      luks.gpgSupport = true;
      luks.devices."luks".device = "/dev/disk/by-uuid/c2e5cd09-b5d7-42cb-a78a-f549edfa0eb4";
    };
  };

  networking = {
    hostName = "uranium";
    useDHCP = false;
  };
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/cbaf293c-c8dc-4586-ba65-73cff3f24468";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/028E-BC0A";
      fsType = "vfat";
    };
  };

  swapDevices = [ ];

  # This node was created in 21.11 days
  system.stateVersion = "21.11";

  # For brightness control
  users.users.spacecadet.extraGroups = [ "video" ];
  # bluetooth
  hardware.bluetooth.enable = true;
  services = {
    blueman.enable = true;
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      wireplumber.enable = true;
    };
    thermald.enable = true;
    fwupd = {
      enable = true;
      extraRemotes = [ "lvfs-testing" ];
    };
    udisks2.enable = true; # NOTE: fwupdmgr uses this to check the boot
  };
  # pipewire config, from https://nixos.wiki/wiki/PipeWire
  security.rtkit.enable = true;
  environment.etc = {
    # battery management
    # powerManagement = {
    #   enable = true;
    #   powertop.enable = true;
    #   cpuFreqGovernor = lib.mkDefault "powersave";
    # };
    "sysconfig/lm_sensors".text = ''
      # Generated by sensors-detect on Mon Jan  3 23:34:14 2022
      # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
      # be loaded/unloaded.
      #
      # The format of this file is a shell script that simply defines variables:
      # HWMON_MODULES for hardware monitoring driver modules, and optionally
      # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

      HWMON_MODULES="coretemp"
    '';
    "fwupd/uefi_capsule.conf".text = lib.mkForce ''
      [uefi_capsule]
      OverrideESPMountPoint=/boot
      DisableCapsuleUpdateOnDisk=true
    '';
  };
  systemd.network.links."10-wifi-lan" = {
    matchConfig.PermanentMACAddress = "14:ac:60:29:76:dd";
    linkConfig.Name = "wifi-lan";
  };

  # Power button handling
  services.logind = {
    powerKey = "suspend";
    powerKeyLongPress = "poweroff";
  };
}
# Uranium specific hardware:1 ends here
