/**
  Gathers Prometheus alerting rules from service manifests.

  Generates:
  - Per-service rule groups from `observability.alerts.prometheusImpl`
  - Per-host "Host Down" rules with severity derived from the services on each host
*/
{ lib, pkgs, ... }:
let
  mkRule = (lib.homelab.getSrvLib "prometheus").mkRule;

  # Import an `alerts.nix` path. Supports both plain attrsets and
  # `{ lib, serviceName, ... }` functions.
  importAlerts =
    srvName: path:
    let
      raw = import path;
    in
    if lib.isFunction raw then
      raw {
        inherit lib;
        serviceName = srvName;
      }
    else
      raw;

  # Expand all alerts from a manifest into a flat list of rule attrsets.
  mkServiceRules =
    srvName: manifest:
    importAlerts srvName manifest.observability.alerts.prometheusImpl
    |> lib.mapAttrsToList (alertLevel: rules: rules |> map (mkRule srvName alertLevel))
    |> lib.flatten;

  # Autogenerated cert expiry alerts for services with `probes.ssl = true`.
  # Uses `min()` across the chain so no `CN` filter is needed.
  mkCertExpiryRules =
    srvName:
    let
      daysToExpire = ''floor((ssl_cert_not_after{resource="srv:${srvName}",dnsnames!=""} - time()) / 86400)'';
    in
    [
      (mkRule srvName "Alert" {
        title = "SSL cert expiring very soon";
        expr = "${daysToExpire} < 2";
        description = "SSL certificate will expire in less than 2 days";
      })
      (mkRule srvName "Informational" {
        title = "Renew SSL cert";
        expr = "${daysToExpire} < 15 unless ${daysToExpire} < 2";
        description = "SSL certificate will expire in less than 15 days";
      })
    ];

in
{
  services.prometheus.ruleFiles = [
    (pkgs.writeText "service-alerts.rules.json" (
      lib.homelab.getManifests
      |> lib.filterAttrs (
        _: m: m.observability.alerts.prometheusImpl or null != null || m.observability.probes.ssl or false
      )
      |> lib.mapAttrsToList (
        srvName: manifest: {
          name = srvName;
          rules =
            lib.optionals (manifest.observability.alerts.prometheusImpl != null) (
              mkServiceRules srvName manifest
            )
            ++ lib.optionals (manifest.observability.probes.ssl or false) (mkCertExpiryRules srvName);
        }
      )
      |> (groups: { inherit groups; })
      |> builtins.toJSON
    ))
  ];
}
