[package]
name = "hyprland-mode-notifier"
version = "0.1.0"
edition = "2021"
description = "Displays desktop notification when mode is entered."

[dependencies]
hyprland = {workspace = true}
notify-rust = {workspace = true}
