#!/bin/sh

# Simple script to pull .nix files from specified IP
scp -o StrictHostKeyChecking=no -o UserKnownHOstsFile=/dev/null *.nix nixos@192.168.1.216:~
ssh -o StrictHostKeyChecking=no -o UserKnownHOstsFile=/dev/null nixos@192.168.1.216 "sudo cp ~/*.nix /mnt/etc/nixos/"
