# [[file:../../new_project.org::*Ethernet][Ethernet:1]]
{
  # Disable autogenerated names
  networking.usePredictableInterfaceNames = false;
  # Systemd-networkd enabled
  networking.useNetworkd = true;

  systemd.network.networks = {
    "20-ethernet" = {
      enable = true;
      name = "eth0";
      dns = [ "1.1.1.1" ];
      # Search domain goes here
      # domains = [ lan.domain ];
      networkConfig = {
        # Address = [ "${local_address}/24" ];
        # Gateway = lan.defaultGateway;
        DHCP = "yes";
        # DNSSEC = "yes";
        # DNSOverTLS = "no";
        # Disable ipv6 explicitly
        # LinkLocalAddressing = "no";
      };
    };
  };
  # I am not using llmnr in my LAN
  services.resolved.llmnr = "false";

  # Any interface being up should be OK
  systemd.network.wait-online.anyInterface = true;
}
# Ethernet:1 ends here
