/**
  Experimental generic networkd module.

  Main purpose -- clear names of physical adapters by calling them "phy-lan"

  Path to non-experimental:
  * Test on fluorine
  * Test on nitrogen
  * Test on carbon
  * Resolve conflicts with existing networkd per-host configs
  * Hydrogen may still be special due to its role as router/fw
  * Mass-apply
  * Fix explosions
*/
{ lib, config, ... }:
let
  inherit (lib.homelab) getOwnHostInNetwork;
in
{
  networking = {
    # Disable autogenerated names
    usePredictableInterfaceNames = false;
    useNetworkd = true;
    enableIPv6 = false;
  };

  systemd.network = {

    networks."10-lan" = {
      enable = true;
      name = "10-lan";
      # Default is to match the name of the network
      matchConfig.Name = lib.mkForce config.systemd.network.links."10-phy-lan".linkConfig.Name;
      networkConfig.DHCP = "yes";
    };

    links."10-phy-lan" = {
      enable = true;
      linkConfig.Name = "phy-lan";
      matchConfig.PermanentMACAddress = (getOwnHostInNetwork "lan").macAddr;
    };
  };

}
