/**
  Experimental generic networkd module.

  Main purpose -- clear names of physical adapters by calling them "phy-lan"
*/
{ lib, config, ... }:
let
  inherit (lib.homelab) getOwnHostInNetwork amInNetwork;
in
{
  networking = {
    # Disable autogenerated names
    usePredictableInterfaceNames = false;
    useNetworkd = true;
    enableIPv6 = false;
  };

  systemd.network = lib.mkIf (amInNetwork "lan") {

    networks."10-lan" = {
      enable = true;
      name = "10-lan";
      # Default is to match the name of the network
      matchConfig.Name = lib.mkForce config.systemd.network.links."10-phy-lan".linkConfig.Name;
      networkConfig = {
        DHCP = "yes";
        # This will also disable ipv6 assigning
        LinkLocalAddressing = "no";
      };
    };

    links."10-phy-lan" = {
      enable = true;
      linkConfig.Name = "phy-lan";
      matchConfig.PermanentMACAddress = (getOwnHostInNetwork "lan").macAddr;
    };
  };

}
